kws = ['evivar',
        'eviten',
        'centro',
        'acopio',
        'ayudar',
        'importante',
        'donativos',
        'colapsar',
        'albergue',
        'comida',
        'daños',
        'necesitan',
        'riesgo',
        'necesidades',
        'necesita']
