# -*- coding: utf-8 -*-

kws = ['evitar',
        'eviten',
        'centro',
        'acopio',
        'ayudar',
        'importante',
        'donativos',
        'colapsar',
        'albergue',
        'comida',
        'daños',
        'necesitan',
        'riesgo',
        'necesidades',
        'necesita',
        'apoyo',
        'urgente',
        'agua',
        'médicos',
        '#busco',
        'busco',
        'tengo',
        '#tengo',
        '#necesito',
        'necesito',
        'tenemos',
        '#tenemos',
        'requieren',
        '#requiero',
        'requiero',
        'necesitamos',
        '#necesitamos']
